apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/bllo-1/k8s-demo.git'
    path: argocd-applications/demo-app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
