{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appName }}-{{ .Values.appEnv }}-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-{{ .Values.appEnv }}-api
{{- end }}
