apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-{{ .Values.appEnv }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}-{{ .Values.appEnv }}-api
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
